---
title: "Programming assignment 3 - template"
format: gfm
date: last-modified
date-format: iso
---

## Load libraries and data

```{r}
#| label: libs
#| message: false
#| warning: false

```

```{r}
#| label: load-data

```



## Descriptive statistics

```{r}
#| label: descriptives
# Calculate means and standard deviations of your English/Spanish vowels


```


## Plots

```{r}
#| label: plot1
# 1. Plot trajectory length as a function of vowel and language 


```





```{r}
#| label: plot2
# 2. Plot F1 as a function of vowel and language




```





```{r}
#| label: plot3
# 3. Plot F2 as a function of vowel and language




```







## Challenge (bonus points)

```{r}
#| label: plot4
# Plot trajectory length in the F1/F2 vowel space

#
# Hints: 
# You will need to do some intense data manipulations first
# Check the help files for pivot_longer (?pivot_longer)
# You will need a combination of group_by, summarize, and pivot_longer 
# (in that order)
#





```




## FREEBIE

```{r}
#| label: plot5
#| fig-retina: 2
#| fig-height: 5
#| out-width: "100%"
#| eval: false
# Plot both vowel spaces together

#
# This assumes your dataframe is called 'vowels'
# Before it will work you need to change 'eval=F' to 'eval=T'
#

vowel_means <- vowels |> 
  group_by(vowel, language) |> 
  summarize(f1_cent = mean(f1_cent), f2_cent = mean(f2_cent)) |> 
  ungroup() |> 
  mutate(order = case_when(vowel == "i" ~ 1, vowel == "a" ~ 2, TRUE ~ 3), 
         vowel = forcats::fct_reorder2(vowel, vowel, order)) |> 
  arrange(order)

vowels |> 
  mutate(vowel = forcats::fct_relevel(vowel, "u", "a", "i")) |> 
  ggplot() +
  aes(x = f2_cent, y = f1_cent, color = language, label = vowel) + 
  geom_text(size = 3.5, alpha = 0.6, show.legend = F) + 
  geom_path(
    data = vowel_means, 
    aes(group = language, lty = language), 
    color = "grey"
  ) + 
  geom_text(data = vowel_means, show.legend = F, size = 7) + 
  scale_y_reverse() + 
  scale_x_reverse() + 
  scale_color_brewer(palette = "Set1") + 
  labs(
    title = "Vowel space comparison", 
    subtitle = "Spectral centroids of English/Spanish cardinal vowels", 
    y = "F1 (hz)", 
    x = "F2 (hz)"
  ) + 
  theme_minimal(base_size = 16)

```
